version: '3'

services:
  app:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    command: realize start
    ports:
      - "3000:3000"
    volumes:
      - "../:/go/src/app"
    tty: true
    depends_on:
      - "db"
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go_sample_db
      MYSQL_USER: go_sample
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local
